---
- name: Verify
  hosts: all

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check whether Linux user is created
      ansible.builtin.shell: |
        set -o pipefail
        ls -l /home | grep {{ item.name }}
      loop: "{{ users }}"
      args:
        executable: /bin/bash
      register: user_exists
      changed_when: false

    - name: Check whether Linux user belongs to 'docker' group
      ansible.builtin.shell: |
        set -o pipefail
        groups {{ item.name }} | grep {{ item.groups }}
      loop: "{{ users }}"
      args:
        executable: /bin/bash
      register: user_groups_belongs_to
      changed_when: false

    - name: Check whether Docker is installed
      ansible.builtin.command: |
        docker --version
      ignore_errors: true
      register: docker_installed
      changed_when: false

    - name: Check whether Git is installed
      ansible.builtin.command: git --version  # noqa command-instead-of-module
      register: git_installed
      changed_when: false

    - name: Check whether vim is installed
      ansible.builtin.command: |
        vim --version
      register: vim_version
      changed_when: false
      ignore_errors: true

    - name: Assert user exists
      ansible.builtin.assert:
        that:
          - "item.stdout != ''"
        fail_msg: "User {{ item.item.name }} does not exist!"
      loop: "{{ user_exists.results }}"

    - name: Assert user belongs to group
      ansible.builtin.assert:
        that:
          - "item.item.groups in item.stdout"
        fail_msg: "User {{ item.item.name }} is not in group {{ item.item.groups }}!"
      loop: "{{ user_groups_belongs_to.results }}"

    - name: Make sure Docker is installed
      ansible.builtin.debug:
        var: docker_installed

    - name: Make sure Git is installed
      ansible.builtin.debug:
        var: git_installed

    - name: Make sure vim is installed
      ansible.builtin.debug:
        var: vim_version

    - name: Assert VNC service is running
      ansible.builtin.assert:
        that:
          - "'vncserver@{{ vnc_display }}.service' in ansible_facts.services"
          - ansible_facts.services['vncserver@{{ vnc_display }}.service'].state == 'running'
        fail_msg: "VNC service is not running: vncserver@{{ vnc_display }}.service"
        success_msg: "VNC service is running: vncserver@{{ vnc_display }}.service"

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
